export const projects = [
  {
    name: "PROJECT USSARI Evening School",
    description: "Education is the most life-changing gift one can provide. Team IOC took charge of supporting children who aspire to be something big by funding their entire education expenses for a lifetime. The project helped them focus more on their studies, as the students have shown excellent academic results. From the past 2 years, Team IOC has been running a free evening school for more than 50 underprivileged students with the help of 3 professional teachers and over 40 youth volunteers from the organization who overlook the development of these students. Students are provided with all the basic facilities, like stationery, books, uniforms, etc. They are also provided with interactive sessions like career guidance or mental health to build their intellect. Future Prospects Our goal is to launch a fully operational school this year, providing quality education to children in our community. We're thrilled to announce that we already have over 50 students eagerly awaiting enrollment in our school. However, to turn this dream into a reality, we need your support. By becoming a monthly donor, you'll play a crucial role in keeping the spirit of Sewa alive. As a monthly donor, you'll receive regular updates on the progress of our school, including milestones reached, challenges overcome, and the positive impact your donations are making in the lives of our students. Your support is not just a financial contribution; it's an investment in the future of our community. Together, we can create a brighter tomorrow for these children, empowering them with the education and opportunities they deserve. Join us in this noble endeavor and be a part of something truly meaningful. Together, we can make a big difference and ensure that every child has access to quality education.",
    image: "../IOC Website pictures/ioc website content/three pillars/Evening school/DSC_8340.JPG"
  },
  {
    name: "Usaari classes",
    description: "Initiators of Change proudly present PROJECT USAARI (Unfolding Skills and Ambitions of Rural India), a groundbreaking initiative aimed at enhancing government schools in Punjab and nurturing the soft skills of their students. Our mission is to digitally equip and structurally fortify 50 government schools across Punjab, creating a safe and healthy environment conducive to learning. At USAARI, our primary focus is on fostering the holistic development and personal growth of children. We provide comprehensive financial and social education. Furthermore, we actively encourage participation in a variety of extracurricular activities. For instance, our flagship event, the PROJECT USAARI YOUTH FEST, held on July 10th, 2023, featured a diverse range of competitions, including Declamation, poetry, Shabad Gayan, painting, Best Out of Waste, and singing. Join us in our journey to transform rural education and empower the youth of Punjab.",
    image: "../IOC Website pictures/ioc website content/three pillars/Usaari class/IMG_20211022_131432.jpg"
  },
  {
    name: "Project Usaari Youth Fest 2023",
    description: "The Initiators of Change successfully hosted the inaugural 'Project Usaari Youth Fest,' celebrating young talent from Punjab's government schools and NGOs. This event not only showcased diverse skills but also emphasized the importance of education and community engagement. Event Highlights: Preliminary Rounds: Participants showcased their skills in essay writing, declamation, singing, poster making, poetry, Shabad Gyan, and creative recycling. Final Showcase: The finale featured outstanding dance, singing, and poetry performances, highlighting the rich cultural and artistic heritage of Punjab. Special Moments: Special children from the Ashirwad NGO participated, enhancing the event with inclusivity. The highlight was a memorable Katha performance by Usaari Evening School students. Impact and Looking Forward: The Youth Fest served as a platform for empowering the youth, fostering inclusivity, and celebrating diversity. Encouraged by this year's success, we plan to expand next year's festival to include more participants and activities. Join us in nurturing the future leaders of Punjab. Your support is invaluable!",
    image: "../IOC Website pictures/ioc website content/three pillars/Education Projects/USAARI Youthfest/393281113_18293901367193454_3537163672505736598_n.jpg"
  },
  
];
