export const projects = [
  {
    name: "Project SAANJH",
    description: "There’s always been a taboo attached to mental health in Indian culture. To eliminate this and spread awareness, the IOC started Project SAANJH. The main motive behind this project was to let people know the importance of mental health. Under this project, the team conducted ‘MAAN MELA’ in remote areas with the help of physiologists, spreading the message that taking therapy isn’t a crime but rather is necessary for one’s mental well-being.",
    image: "../../IOC Website pictures/ioc website content/three pillars/Project Saanjh/_DSC2548.JPG"
  },
  {
    name: "I Vote, I LEAD",
    description: "An aware voter can change who leads his or her country. Keeping the 2017 Punjab Assembly elections in mind, the team started a campaign called ‘I Vote, I Lead’ to make the youth aware of the power of voting. The team worked in collaboration with District election officers as the flag bearers of their SVEEP activities. Initiators of Change have been honored by the Election Commission of India for working at such a mass level for youth voter awareness. More than 3 lakh people are made aware by the team through college seminars, awareness rallies, short plays, and flash mobs. This record was recognized by the India Book of Records. This initiative was recognized by the Election Commission of India, which thanked the volunteers at Team IOC for spreading voter awareness. The campaign was marked as one of the most successful voter awareness campaigns in Punjab, and the team was honored by District Electoral Officer Ludhiana and Chief Electoral Officer Punjab on National Voters Day 2017. A knowledgeable voter has the potential to influence the leadership of their nation. The 'I Vote, I Lead' campaign, initiated by the IOC, aims to enlighten people about the significance of their vote. During the 2017 Punjab Assembly elections, the team launched 'I Vote, I Lead' to boost youth voter turnout. Working closely with district election officers, they led SVEEP activities. Their efforts were lauded as one of Punjab's most successful voter awareness campaigns, earning recognition from authorities on National Voters Day 2017. Engaging over 35,000 youths in three months, they set a national record for the largest gathering of youth voter card holders, acknowledged by the India Book of Records. Expanding nationally in 2019 for the general elections, the organization reached 250,000 youth voters, creating over 100,000 first-time voters and promoting smart voting awareness. Recognized by the Election Commission of India, Initiators of Change were commended for their extensive work in Ludhiana district. Continuing this practice for the 2024 Lok Sabha elections this year too, through college seminars, awareness rallies, short plays, and flash mobs, the team has reached out to over 300,000 individuals. This effort was acknowledged by the Election Commission of India, which appreciated the volunteers at the IOC for their role in promoting voter awareness.",
    image: "../../IOC Website pictures/ioc website content/three pillars/I vote i lead/Copy of 16128788_1205922192790544_1740987231_n.jpg"
  },
  {
    name: "SMYC",
    description: "SMYC (Speaking Mind Youth Conclave) stands as one of north India’s biggest youth gatherings, aimed at fostering engagement among the younger generations. With a history of over 1000 participants from the Tricity area, the conclave serves as a melting pot of ideas and inspiration. Notably, SMYC has hosted speakers like Sushant Singh Rajput, Kunal Kapoor, Nirmal Sarin, Deepa Malik, RJ Abhimanyu, and others. These distinguished personalities have shared their journeys and insights, motivating the youth to strive for excellence and make a positive impact on society. Each conclave is carefully curated to address pertinent topics, offering a platform for young minds to express themselves and learn from one another.",
    image: "../../IOC Website pictures/ioc website content/three pillars/Awareness projects/SMYC/Copy of DSC07975.JPG"
  },
];
